/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package com.jocile.catalogo.view;

/**
 *
 * @author joc
 */
public class JanelaRadio extends javax.swing.JInternalFrame {

    /** Creates new form JanelaRadio */
    public JanelaRadio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbtCafe = new javax.swing.JRadioButton();
        rbtCha = new javax.swing.JRadioButton();
        btVerificar = new javax.swing.JButton();
        lbResultado = new javax.swing.JLabel();

        buttonGroup1.add(rbtCafe);
        rbtCafe.setText("Café");

        buttonGroup1.add(rbtCha);
        rbtCha.setText("Chá");

        btVerificar.setText("Verificar");
        btVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificarActionPerformed(evt);
            }
        });

        lbResultado.setText("Nenhuma opção selecionada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResultado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtCafe)
                            .addComponent(btVerificar))
                        .addGap(18, 18, 18)
                        .addComponent(rbtCha)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtCafe)
                    .addComponent(rbtCha))
                .addGap(32, 32, 32)
                .addComponent(btVerificar)
                .addGap(39, 39, 39)
                .addComponent(lbResultado)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificarActionPerformed
        if (rbtCafe.isSelected()){
            lbResultado.setText("Café foi selecionado");
        }
        if (rbtCha.isSelected()){
            lbResultado.setText("Chá foi selecionado");
        }
    }//GEN-LAST:event_btVerificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVerificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JRadioButton rbtCafe;
    private javax.swing.JRadioButton rbtCha;
    // End of variables declaration//GEN-END:variables

}
